default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: rekapku
  host: localhost
  username: root
  password: mymother
  timeout: 5000
  pool: 5

test:
  adapter: sqlite3 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
